image:
  file: .gitpod.dockerfile

tasks:
- command: |
    npm i -g @angular/cli
    npm i -g nx
    npm install
 
 vscode:
  extensions:
    - nrwl.angular-console
    - loiane.angular-extension-pack
    - mikael.angular-beastcode
